---
- name: "ROLLBACK | Centrais e remotos via Netmiko(TELNET)"
  hosts: central_routers
  gather_facts: no

  vars_files:
    - "{{ playbook_dir }}/../group_vars/central_routers.yml"

  vars:
    venv_python: "{{ playbook_dir }}/../.venv/bin/python"
    runner: "{{ playbook_dir }}/../scripts/netmiko_runner.py"
    logs_dir: "{{ playbook_dir }}/../logs"

  tasks:
    - name: "LOG | Alvo (inventory + IP)"
      ansible.builtin.debug:
        msg: "Alvo={{ inventory_hostname }} ip={{ ansible_host }}"

    - name: "Executar rollback em check mode"
      ansible.builtin.command:
        argv:
          - "{{ venv_python }}"
          - "{{ runner }}"
          - "--mode"
          - "rollback"
          - "--host"
          - "{{ ansible_host }}"
          - "--username"
          - "{{ net_username }}"
          - "--password"
          - "{{ net_password }}"
          - "--hostvars"
          - "{{ playbook_dir }}/../host_vars/{{ inventory_hostname }}.yml"
          - "--logs-dir"
          - "{{ logs_dir }}"
          - "--dry-run"
      register: nm
      changed_when: false
      failed_when: nm.rc != 0
      when: ansible_check_mode
      check_mode: no

    - name: "Executar rollback em modo normal"
      ansible.builtin.command:
        argv:
          - "{{ venv_python }}"
          - "{{ runner }}"
          - "--mode"
          - "rollback"
          - "--host"
          - "{{ ansible_host }}"
          - "--username"
          - "{{ net_username }}"
          - "--password"
          - "{{ net_password }}"
          - "--hostvars"
          - "{{ playbook_dir }}/../host_vars/{{ inventory_hostname }}.yml"
          - "--logs-dir"
          - "{{ logs_dir }}"
      register: nm
      changed_when: false
      failed_when: nm.rc != 0
      when: ansible_check_mode
      check_mode: no

    - name: "Resultado (JSON)"
      ansible.builtin.debug:
        var: nm.stdout | from_json
      when: nm is defined and nm.stdout is defined and nm.stdout | length > 0
